version: '3'
services:
  lazydocker:
    build:
      context: https://github.com/khulnasoft/lazydocker.git
      args:
        BASE_IMAGE_BUILDER: golang
        GOARCH: amd64
        GOARM:
    image: khulnasoft/lazydocker
    container_name: lazydocker
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/.config/khulnasoft/lazydocker
