name: terrasecurity
on: [push]

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrasec-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan
      id: terrascan
      uses: khulnasoft/terrasec-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
